import React, { useState, useEffect } from 'react';
import { useAuth } from '../../auth/AuthContext';
import { Link } from 'react-router-dom';
import PageHeader from '../../components/common/PageHeader';
import StatCard from '../../components/common/StatCard';
import Card from '../../components/common/Card';
import Button from '../../components/common/Button';
import ActivityTimeline from '../../components/common/ActivityTimeline';
import { getEngineerStats } from '../../api/dashboard';
import {
  UserPlus,
  CheckCircle2,
  Send,
  Clock,
  Calendar,
  FileText,
  ArrowRight,
  Sparkles,
  ChevronRight,
  ShieldCheck,
  Users
} from 'lucide-react';

export const EngineerDashboard = () => {
  const { user } = useAuth();
  const [stats, setStats] = useState({
    newCandidates: 0,
    pendingVerification: 0,
    sentToInstructors: 0,
    awaitingInstructorResponse: 0,
    interviewsCompleted: 0,
    reportsReady: 0
  });

  useEffect(() => {
    getEngineerStats().then(setStats);
  }, []);

  const pipelineStages = [
    { title: 'Candidate Intake', count: stats.newCandidates, icon: UserPlus, color: 'var(--primary)', link: '/engineer/candidates/intake' },
    { title: 'Verification', count: stats.pendingVerification, icon: CheckCircle2, color: 'var(--warning)', link: '/engineer/candidates/pending' },
    { title: 'Instructor Routing', count: stats.sentToInstructors, icon: Send, color: 'var(--accent-purple)', link: '/engineer/assignments/sent' },
    { title: 'AI Interview', count: stats.interviewsCompleted, icon: Calendar, color: 'var(--info)', link: '/engineer/interviews/in-progress' },
    { title: 'Evaluation Report', count: stats.reportsReady, icon: FileText, color: 'var(--success)', link: '/engineer/reports' }
  ];

  return (
    <div>
      <PageHeader
        title={`Good morning, ${user?.fullName?.split(' ')[0] || 'Engineer'}`}
        subtitle="Manage candidate intake, verification, routing, and interview progress."
        badge={
          <span style={{ fontSize: '0.75rem', fontWeight: '700', padding: '0.2rem 0.6rem', borderRadius: 'var(--radius-full)', background: 'var(--info-bg)', border: '1px solid var(--info-border)', color: 'var(--info)' }}>
            INTERVIEW ENGINEER
          </span>
        }
        actions={
          <Link to="/engineer/candidates/intake">
            <Button variant="primary" size="sm" icon={UserPlus}>
              New Candidate Intake
            </Button>
          </Link>
        }
      />

      {/* KPI Stats Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.25rem', marginBottom: '2rem' }}>
        <StatCard
          title="New Candidates"
          value={stats.newCandidates}
          subtitle="Intake items"
          icon={UserPlus}
          color="indigo"
        />
        <StatCard
          title="Pending Verification"
          value={stats.pendingVerification}
          subtitle="Awaiting resume check"
          icon={Clock}
          color="amber"
        />
        <StatCard
          title="Sent to Instructors"
          value={stats.sentToInstructors}
          subtitle="Assigned for review"
          icon={Send}
          color="purple"
        />
        <StatCard
          title="Reports Ready"
          value={stats.reportsReady}
          subtitle="Generated by AI engine"
          icon={FileText}
          color="emerald"
        />
      </div>

      {/* Recruitment Pipeline Visual Workflow */}
      <Card
        title="Candidate Lifecycle & Routing Pipeline"
        subtitle="End-to-end recruitment flow from intake to instructor report review"
        style={{ marginBottom: '2rem' }}
      >
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
          gap: '1rem',
          marginTop: '1rem'
        }}>
          {pipelineStages.map((stage, idx) => {
            const Icon = stage.icon;
            return (
              <Link key={idx} to={stage.link} style={{ textDecoration: 'none' }}>
                <div
                  style={{
                    padding: '1.25rem',
                    borderRadius: 'var(--radius-md)',
                    background: 'rgba(255, 255, 255, 0.02)',
                    border: '1px solid var(--border-color)',
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'space-between',
                    minHeight: '130px',
                    transition: 'all 0.2s ease',
                    position: 'relative'
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.borderColor = 'var(--border-highlight)';
                    e.currentTarget.style.transform = 'translateY(-2px)';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.borderColor = 'var(--border-color)';
                    e.currentTarget.style.transform = 'none';
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div
                      style={{
                        padding: '0.5rem',
                        borderRadius: 'var(--radius-sm)',
                        background: 'rgba(255, 255, 255, 0.05)',
                        color: stage.color
                      }}
                    >
                      <Icon size={18} />
                    </div>
                    <span style={{ fontSize: '1.4rem', fontWeight: '800', color: 'var(--text-primary)' }}>
                      {stage.count}
                    </span>
                  </div>

                  <div>
                    <div style={{ fontSize: '0.85rem', fontWeight: '600', color: 'var(--text-primary)', marginTop: '0.75rem' }}>
                      {stage.title}
                    </div>
                    <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '2px', marginTop: '0.2rem' }}>
                      Stage {idx + 1} <ChevronRight size={12} />
                    </div>
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
      </Card>

      {/* Two Column Section: Quick Actions + Activity */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '1.5rem' }}>
        <Card title="Quick Actions" subtitle="Frequent engineer intake workflows">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', marginTop: '0.5rem' }}>
            <Link to="/engineer/candidates/intake" style={{ textDecoration: 'none' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0.875rem 1rem', borderRadius: 'var(--radius-md)', background: 'rgba(255, 255, 255, 0.02)', border: '1px solid var(--border-color)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <UserPlus size={18} color="var(--primary)" />
                  <div>
                    <div style={{ fontSize: '0.875rem', fontWeight: '600', color: 'var(--text-primary)' }}>Add Candidate & Upload Resume</div>
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Initiate intake and AI resume analysis (Phase 5).</div>
                  </div>
                </div>
                <ArrowRight size={16} color="var(--text-muted)" />
              </div>
            </Link>

            <Link to="/engineer/candidates/pending" style={{ textDecoration: 'none' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0.875rem 1rem', borderRadius: 'var(--radius-md)', background: 'rgba(255, 255, 255, 0.02)', border: '1px solid var(--border-color)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <CheckCircle2 size={18} color="var(--warning)" />
                  <div>
                    <div style={{ fontSize: '0.875rem', fontWeight: '600', color: 'var(--text-primary)' }}>Verify Pending Candidates</div>
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Review parsed candidate credentials and verify data.</div>
                  </div>
                </div>
                <ArrowRight size={16} color="var(--text-muted)" />
              </div>
            </Link>

            <Link to="/engineer/assignments" style={{ textDecoration: 'none' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0.875rem 1rem', borderRadius: 'var(--radius-md)', background: 'rgba(255, 255, 255, 0.02)', border: '1px solid var(--border-color)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <Send size={18} color="var(--accent-purple)" />
                  <div>
                    <div style={{ fontSize: '0.875rem', fontWeight: '600', color: 'var(--text-primary)' }}>Assign to Instructor</div>
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Route verified candidate to domain evaluators.</div>
                  </div>
                </div>
                <ArrowRight size={16} color="var(--text-muted)" />
              </div>
            </Link>

            <Link to="/engineer/reports" style={{ textDecoration: 'none' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0.875rem 1rem', borderRadius: 'var(--radius-md)', background: 'rgba(255, 255, 255, 0.02)', border: '1px solid var(--border-color)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <FileText size={18} color="var(--success)" />
                  <div>
                    <div style={{ fontSize: '0.875rem', fontWeight: '600', color: 'var(--text-primary)' }}>Deliver Assessment Reports</div>
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Forward finished AI evaluations to instructors.</div>
                  </div>
                </div>
                <ArrowRight size={16} color="var(--text-muted)" />
              </div>
            </Link>
          </div>
        </Card>

        {/* Activity Stream */}
        <Card title="Recent Activity" subtitle="Real-time candidate routing updates">
          <ActivityTimeline
            emptyMessage="No candidate activity yet. Real-time updates will stream during candidate processing."
            events={[]}
          />
        </Card>
      </div>
    </div>
  );
};

export default EngineerDashboard;
