package com.agenthire.entity.enums;

public enum NotificationType {
    CANDIDATE_ASSIGNED,
    CANDIDATE_ASSIGNMENT_ACCEPTED,
    CANDIDATE_ASSIGNMENT_DECLINED,
    CANDIDATE_VERIFIED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_STARTED,
    INTERVIEW_COMPLETED,
    REPORT_READY,
    REPORT_SENT,
    SYSTEM
}

