import React from 'react';
import PageHeader from '../../components/common/PageHeader';
import DataTable from '../../components/common/DataTable';
import StatusBadge from '../../components/common/StatusBadge';

export const InstructorReports = () => {
  const columns = [
    { header: 'Candidate', accessor: 'candidateName' },
    { header: 'Interview Title', accessor: 'title' },
    { header: 'Technical Score', accessor: 'techScore' },
    { header: 'Coding Score', accessor: 'codingScore' },
    { header: 'Behavioral Score', accessor: 'behavioralScore' },
    {
      header: 'Human Review Decision',
      accessor: 'status',
      render: (row) => <StatusBadge status={row.status || 'FINAL_REVIEW'} size="sm" />
    }
  ];

  return (
    <div>
      <PageHeader
        title="Candidate Assessment & Evaluation Reports"
        subtitle="Review AI agent rubrics, inspect candidate responses, and record final hiring decisions."
      />

      <DataTable
        columns={columns}
        data={[]}
        emptyTitle="No evaluation reports pending review"
        emptyDescription="Assessment reports generated by the AI evaluation pipeline will appear here for instructor sign-off."
      />
    </div>
  );
};

export default InstructorReports;
